#!/usr/bin/env python3
"""Inventory actual Python distribution bytes without importing the model adapter.

Run with the adapter's interpreter, not with a different evaluator environment.
This binds a controlled, immutable local environment; it is not an attestation
against hostile Python startup hooks or concurrent filesystem modification.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import os
import re
import sys
from importlib import metadata
from pathlib import Path, PurePosixPath
from urllib.parse import unquote, urlparse


def file_record(path):
    path = Path(os.path.abspath(path))
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return {
        "path": str(path),
        "resolved_path": str(path.resolve()),
        "size_bytes": path.stat().st_size,
        "sha256": digest.hexdigest(),
    }


def collect_environment(root):
    root = Path(root).resolve()
    distributions, files = [], {}
    names = set()
    for dist in metadata.distributions():
        name = re.sub(r"[-_.]+", "-", dist.metadata["Name"]).lower()
        if name in names:
            raise ValueError(f"duplicate installed distribution: {name}")
        names.add(name)
        # Parse RECORD ourselves: some importlib.metadata versions omit missing
        # installed files from dist.files, which would hide an incomplete install.
        record = dist.read_text("RECORD")
        if not record:
            raise ValueError(f"distribution has no auditable wheel RECORD: {name}")
        installed = [PurePosixPath(row[0]) for row in csv.reader(io.StringIO(record)) if row]
        if not installed:
            raise ValueError(f"distribution has no auditable file inventory: {name}")
        direct_url = json.loads(dist.read_text("direct_url.json") or "{}")
        if direct_url.get("dir_info", {}).get("editable"):
            url = urlparse(direct_url.get("url", ""))
            editable_root = Path(unquote(url.path)).resolve()
            if name != "gemma-system-one" or url.scheme != "file" or editable_root != root:
                raise ValueError(f"unbound editable distribution: {name}")
            # The current project's src/s1 sources are additionally bound by RuntimeGuard.
        paths = []
        candidates = {Path(os.path.abspath(dist.locate_file(item))) for item in installed}
        top_levels = {
            item.parts[0]
            for item in installed
            if item.parts and item.parts[0] not in (".", "..", "/")
        }
        for top_level in sorted(top_levels):
            # Include added modules/extensions in distribution-owned directories, not
            # merely the files named by RECORD. Never recursively scan ../bin.
            directory = Path(dist.locate_file(top_level))
            if directory.is_dir():
                candidates.update(path for path in directory.rglob("*") if path.is_file())
        for path in sorted(candidates):
            item = path
            # Generated bytecode is not stable across warmup. Its source remains bound.
            if str(item).endswith((".pyc", ".pyo")) or "__pycache__" in item.parts:
                continue
            if not path.is_file():
                raise ValueError(f"installed distribution file is missing: {name}: {item}")
            key = str(path)
            if key not in files:
                files[key] = file_record(path)
            paths.append(key)
        if not paths:
            raise ValueError(f"distribution has an empty audited inventory: {name}")
        distributions.append({"name": name, "version": dist.version, "files": sorted(set(paths))})
    return {
        "schema_version": 1,
        "scope": (
            "all installed distribution files except generated bytecode; "
            "project sources pinned separately"
        ),
        "python": sys.version,
        "executable": os.path.abspath(sys.executable),
        "prefix": sys.prefix,
        "base_prefix": sys.base_prefix,
        "sys_path": sys.path,
        "import_environment": {
            name: os.environ.get(name)
            for name in (
                "PYTHONPATH",
                "PYTHONHOME",
                "VIRTUAL_ENV",
                "LD_LIBRARY_PATH",
                "DYLD_LIBRARY_PATH",
                "DYLD_FALLBACK_LIBRARY_PATH",
            )
        },
        "distributions": sorted(distributions, key=lambda item: item["name"]),
        "files": [files[key] for key in sorted(files)],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(collect_environment(args.root), sort_keys=True, allow_nan=False))


if __name__ == "__main__":
    main()
